### ISSUE TITLE
Unusual behavior With Image widget

### ISSUE THREAD

**Issue by teknology** [elementor/hello-theme-child#10]
After activating the elementor child theme, the image widget no longer loads the site logo which is dynamically loaded. The image widget is used  because the site logo widget doesn't allow for changing the link url.

This is with the main Hello theme 
https://prnt.sc/qiqzph

This is when the child theme is activated.
https://prnt.sc/qir06h

**Comment by cfoellmann** [comment]
you need to set the sitelogo again after switching to the child theme.

**Comment by teknology** [comment]
That's not really a fix.
