### ISSUE TITLE
 style.css file doesn't work

### ISSUE THREAD

**Issue by ghost** [elementor/hello-theme-child#12]
Hi there,

I just install this child theme and have activated it.
The functions.php file works perfectly when I added some functions.

I have an issue with the style.css  files.

Nothing happens when I apply some code.

I installed the child theme without changing anything else. 

Do you have any idea? What can I try?

Thanks for your help.  🙏

**Comment by mentzelia** [comment]
It's ok, I found in the official Wordpress Codex some code and it's work.

`add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
function my_theme_enqueue_styles() {
 
    $parent_style = 'hello-elementor'; 
 
    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}`

**Comment by 2amredart** [comment]
The version in functions.php code is 1.0.1
The version in style.css code is 1.0.0

When I made them the same number (1.0.1), all is good

**Comment by jonathandhn** [comment]
Have the same here...

**Comment by Mramorov** [comment]
+1

**Comment by EricSleep** [comment]
Hi,

I downloaded yesterday the child theme and after instalation and activation, the function.php is working but the style.css doesn't work for me, i can't put any modifications there, i have to use the aditional CSS from Wordpress.

Anyone to help me to understand and fix this style.css?

thanks,
Eric

**Comment by EricSleep** [comment]
Hi,
 a little update of my issue if someone can help me to understand why it's not working the child theme for me.
 So, i installed WP from scratch + Hello Elementor parent and child theme on local without any customs, and it's working well, so i don't understand why it's not working on the web ?
Thx for your help!
Eric

**Comment by rami-elementor** [comment]
All the information you need is documented in the [Child Themes handbook](https://developer.wordpress.org/themes/advanced-topics/child-themes/).

**Comment by Milad-jfr** [comment]
seems the problem is with style version ,
check this out :
https://github.com/elementor/hello-theme-child/issues/48#issuecomment-2180472926

**Comment by Milad-jfr** [comment]
seems the problem is with style version and cache related something ,
check this out :
https://github.com/elementor/hello-theme-child/issues/48#issuecomment-2180524058
