### ISSUE TITLE
background 

### ISSUE THREAD

**Issue by ahmadkholil168** [elementor/hello-theme-child#14]
**hello theme cannot print background color or image**
![1](https://user-images.githubusercontent.com/61233192/81026142-53810800-8ea3-11ea-8fb9-f3534345ab8c.png)
![2](https://user-images.githubusercontent.com/61233192/81026155-5aa81600-8ea3-11ea-811e-fa733c3be03e.png)

**If it is another topic, there is no problem**
![3](https://user-images.githubusercontent.com/61233192/81026194-77444e00-8ea3-11ea-96a4-7918338353f9.png)
![4](https://user-images.githubusercontent.com/61233192/81026199-7a3f3e80-8ea3-11ea-9472-ed053b0e5248.png)

**Comment by rami-elementor** [comment]
Please create a new issue in english.
