### ISSUE TITLE
Issue when updating: Some pages missing styles

### ISSUE THREAD

**Issue by ghost** [elementor/hello-theme-child#15]
Hello all,

I am using Elementor Pro and the Hello Child Theme for a few of my client sites.

When I update Elementor Pro or WordPress, once in a while, my styles go missing on some of the pages. It is very inconsistent, and I am trying to pinpoint when it happens.

Oddly, it doesn't even happen on all of my sites either.

Once I go into the editor for the page missing style, make a small change and update, it fixes the issue.

Is anyone else experiencing this?

Thank you!

**Comment by rami-elementor** [comment]
You don't need to editor the page to generate styles, simply go to Elementor > Tools and press the "Regenerate Files & Data" button.
