### ISSUE TITLE
Outdated copies of some WooCommerce template files

### ISSUE THREAD

**Issue by vandijks** [elementor/hello-theme-child#25]
I get the message: "Your theme (Hello Elementor Child) contains outdated copies of some WooCommerce template files."

I am running versions 1.0.1.

When browsing to Woocommerce \ status \ templates it says:

hello-theme-child-master/woocommerce/emails/plain/email-order-items.php version 3.7.0 is out of date. The core version is 5.2.0,

**Comment by zanstro** [comment]
Any update on this?

**Comment by dexit** [comment]
WEll well well seems manual update as usual...

**Comment by rami-elementor** [comment]
You need to contact the developers that created the child theme for your site.

Seems like he added some woocommerce-related templates files, and some of theme should be updated from version 3.7.0 to 5.2.0.

The original "hello-theme-child" theme doesn't include those files.
