### ISSUE TITLE
Enqueue Priority

### ISSUE THREAD

**Issue by webthread** [elementor/hello-theme-child#3]
You really want the child-theme css loading last. This way we don't have to use !important or add extra classes to override the natural cascade. 
Simply change the add_action in functions.php to
`add_action( 'wp_enqueue_scripts', 'hello_elementor_child_enqueue_scripts',99 );`

**Comment by ellegaarddk** [comment]
Why haven't this been implemented? It's so easy to do - but it can be really frustrating trying to figure out what's going on until you figure out what's wrong... :(
I grab this every time, but once in a while I forget to make this small change and waste time trying to figure out why it's not working like it normally does.

**Comment by drawcard** [comment]
Have created a pull request to fix this. At the moment I have to use !important everywhere in my theme CSS to see any change happen, which is not great.

https://github.com/elementor/hello-theme-child/pull/8

**Comment by RVAtraining** [comment]
Thanks everyone for this thread. I just lost 5 hours trying to figure out how to allow the child theme to override the parent theme. Phew! You saved me!

**Comment by drawcard** [comment]
Yeah hopefully the PR will get merged soon so I don't have to copypasta every time I set a theme up 👍
