### ISSUE TITLE
Error loading the theme

### ISSUE THREAD

**Issue by raylangivens1** [elementor/hello-theme-child#31]
I was doing some updates on my hosting when the loading of my website failed.

This is the error.

`Fatal error: Uncaught Error: Call to undefined function cb_child_process_location() in /homepages/5/d848895393/htdocs/clickandbuilds/WordPress/Mywebsite/wp-content/themes/hello-elementor-child/header.php:23 Stack trace: #0 /homepages/5/d848895393/htdocs/clickandbuilds/WordPress/Mywebsite/wp-includes/template.php(770): require_once() #1 /homepages/5/d848895393/htdocs/clickandbuilds/WordPress/Mywebsite/wp-includes/template.php(716): load_template('/homepages/5/d8...', true, Array) #2 /homepages/5/d848895393/htdocs/clickandbuilds/WordPress/Mywebsite/wp-includes/general-template.php(48): locate_template(Array, true, true, Array) #3 /homepages/5/d848895393/htdocs/clickandbuilds/WordPress/Mywebsite/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(9): get_header() #4 /homepages/5/d848895393/htdocs/clickandbuilds/WordPress/Mywebsite/wp-includes/template-loader.php(106): include('/homepages/5/d8...') #5 /homepages/5/d848895393/htdocs/clickandbuilds/WordPress/Mywebsite/wp-blog-header.php(19): require_once('/homepages/5/d8...') # in /homepages/5/d848895393/htdocs/clickandbuilds/WordPress/Mywebsite/wp-content/themes/hello-elementor-child/header.php on line 23 `

If I switch the theme to the original (Hello-Elementor) the body loads successfully but it doesnt load the header, I dont know why.

Any clue of where is the issue or how can I fix the child theme?

Thanks in advice.

**Comment by rami-elementor** [comment]
Your website is using a child theme which is using an undefined `cb_child_process_location()` function.

See `hello-elementor-child/header.php` file, line 23.

Or contact the developer that created this child theme for you.
