### ISSUE TITLE
Add check for handling taxonomy templates

### ISSUE THREAD

**Issue by bbua97** [elementor/hello-theme-child#32]
Hey there,

I have problems using an officialy by WooCommerce Supported Plugin called Sensei LMS. There are some pages shown a "content not found" error. I talked to the developers and they checked the Hello Elementor theme code and that was the answer:

"I took a look at the [Hello Elementor theme code](https://github.com/elementor/hello-theme/blob/master/index.php#L33) and it looks like Elementor doesn’t have a check for handling taxonomy templates, which is a problem because a module is a taxonomy. Since there’s no check for it, it falls through to displaying its 404 page."

I found more people struggling with this so it would be great if you could fix this finally.

Note: I copied this from the elementor/hello-theme repository because there's no reaction, nothing.

**Comment by rami-elementor** [comment]
> "I took a look at the [Hello Elementor theme code](https://github.com/elementor/hello-theme/blob/master/index.php#L33) and it looks like Elementor doesn’t have a check for handling taxonomy templates, which is a problem because a module is a taxonomy. Since there’s no check for it, it falls through to displaying its 404 page."

Correct me if I'm wrong but "taxonomy" fallback is an "archive" page, and the parent theme covers this at:
https://github.com/elementor/hello-theme/blob/master/index.php#L23

See the WordPress template hierarchy:
https://developer.wordpress.org/themes/basics/template-hierarchy/#visual-overview
