### ISSUE TITLE
Needs to be updated for FontAwesome 6

### ISSUE THREAD

**Issue by patrickhealy** [elementor/hello-theme-child#34]
Right now, 4.7 seems to be what it's tailored to. Not sure if it matters or if it would just be documentation but it would be nice for clarity

**Comment by kwsim539** [comment]
Agreed. Or at the very least version 5.15.4.

**Comment by rami-elementor** [comment]
Hello Theme doesn't registers FontAwesome.

The Elementor plugin is the one that registers and uses FontAwesome.

Therefore I'm closing the issue.

**Comment by patrickhealy** [comment]
@rami-elementor , is there any way you could perhaps help me get this in front of the right person over at Elementor? This issue has been an issue for well over a year.  It's a shame we can't use the full FontAwesome product due to a neglected integration.
