### ISSUE TITLE
functions.php is not PHP 8 compatible

### ISSUE THREAD

**Issue by Wyzkiewicz** [elementor/hello-theme-child#39]
Attempting to use Hello Elementor Child theme with PHP 8.0 and higher throws a fatal exception.  The error thrown is:

[07-Mar-2023 00:39:28 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /var/www/html/wordpress/wp-content/themes/hello-theme-child-master/functions.php:33
Stack trace:
#0 /var/www/html/wordpress/wp-settings.php(585): include()
#1 /var/www/html/wordpress/wp-config.php(103): require_once('...')
#2 /var/www/html/wordpress/wp-load.php(50): require_once('...')
#3 /var/www/html/wordpress/wp-blog-header.php(13): require_once('...')
#4 /var/www/html/wordpress/index.php(17): require('...')
#5 {main}
  thrown in /var/www/html/wordpress/wp-content/themes/hello-theme-child-master/functions.php on line 33

**Comment by Wyzkiewicz** [comment]
Please close this I think I see what is going on and the bit of code throwing the error is not in the delivered functions.php.

**Comment by kwsim539** [comment]
@KingYes @pless84 Can we close this?

**Comment by Wyzkiewicz** [comment]
Absolutely, I discovered that the functions.php had been modified and the
portion that triggered the error was not in the original.

Joe
