### ISSUE TITLE
Create translate for child theme

### ISSUE THREAD

**Issue by datverse** [elementor/hello-theme-child#42]
Hi, 
I want create some translate text for my child theme.
I use Poedit to create hello-elementor-child-vi.PO and hello-elementor-child-vi.MO files. I put them in /languages folder
In child theme I create PHP code:

```
function __load_child_theme_textdomain(): void {
		load_child_theme_textdomain( 'hello-elementor', get_stylesheet_directory() . '/languages' );
}

add_action( 'after_setup_theme', '__load_child_theme_textdomain'  );

add_shortcode( 'echo_translate', '__echo_translate_shortcode'  );

function __echo_translate_shortcode(): string {
		return __( 'Something', 'hello-elementor' );
}
```

Go to Font Page, change page to Vietnamese, Call Shortcode => The string not translate

Can you help me?
Thanks

**Comment by rami-elementor** [comment]
Please read more information in the [Child Themes handbook](https://developer.wordpress.org/themes/advanced-topics/child-themes/#internationalization).
