### ISSUE TITLE
hello-theme-child plugin 

### ISSUE THREAD

**Issue by dezgnme** [elementor/hello-theme-child#43]
Hello, 

Plugin won't installed.  See below.

Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin installation failed.

**Comment by StenderIternum** [comment]
@dezgnme It's not a plugin though... It's a theme

**Comment by dezgnme** [comment]
Thanks I fixed it already.

**Comment by nicholaszein** [comment]
Closing as solved.
