### ISSUE TITLE
Where is the child theme file?

### ISSUE THREAD

**Issue by foolstuck** [elementor/hello-theme-child#45]
Where is the child theme file?

**Comment by CaptainSeebas** [comment]
You can find it under "code" in the top-right hand, above the "<> code" tab of the project, then click download zip, as shown below:

<img width="1023" alt="Github file download" src="https://github.com/elementor/hello-theme-child/assets/152170890/6650209e-68e7-4f00-8ad2-67e8499e48c6">

Hope it helps!

**Comment by foolstuck** [comment]
Thank you for the detailed instructions!
